### ISSUE TITLE
springboot-japidocs项目启动生成Api文档工具类时报空指针异常

### ISSUE THREAD

**Issue by Mingxiangyu** [ruiyeclub/SpringBoot-Hello#6]
需要在Docs.buildHtmlDocs(config);前添加		config.setOpenReflection(Boolean.FALSE);

public class DocUtil {

	public static void main(String[] args) {
		DocsConfig config = new DocsConfig();
    // 项目根目录
    config.setProjectPath("F:\\gitWorkSpace\\SpringBoot-Hello\\springboot-japidocs");
		// 项目名称
		config.setProjectName("springboot-japidocs");
		// 声明该API的版本
		config.setApiVersion("V1.0.3");
		//生成API 文档所在目录
		config.setDocsPath("C:\\新建文件夹1");
		// 配置自动生成
		config.setAutoGenerate(Boolean.TRUE);
		// 执行生成文档
		config.addPlugin(new MarkdownDocPlugin());
		config.setOpenReflection(Boolean.FALSE);
		Docs.buildHtmlDocs(config);
	}

**Comment by ruiyeclub** [comment]
需要将这个项目单独打开 你看一下日志就可以发现 这个工具读取路径的时候 读到了别的项目
